services:
  - type: web
    name: anonymous-chat-api
    env: docker
    dockerfilePath: ./apps/api/Dockerfile
    dockerContext: .
    plan: free
    healthCheckPath: /healthz
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "4000"
      - key: DATABASE_URL
        sync: false
      - key: REDIS_URL
        sync: false
      - key: JWT_ACCESS_SECRET
        generateValue: true
      - key: JWT_REFRESH_SECRET
        generateValue: true
      - key: TOKEN_HASH_SECRET
        generateValue: true
      - key: COOKIE_SECRET
        generateValue: true
      - key: APP_ORIGIN
        value: "https://c-anonymous-chat-web.vercel.app"
